services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
    depends_on:
      - mongodb
  mongodb:
    image: bitnami/mongodb
    volumes:
      - ./data:/data/db
    environment:
      - PUID=1000
      - PGID=1000
  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm run start
    volumes:
      - ./client/src/:/app/src/
    depends_on:
      - server
